PROJECT := test
CSMC    :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/stateos/make/stm8sdiscovery/makefile.csmc
#----------------------------------------------------------#
include $(COMMON)/api/makefile
include $(COMMON)/device/makefile
include $(COMMON)/startup/makefile
#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
