PROJECT := test
SDCC    :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/stateos/make/stm8sdiscovery/makefile.sdcc
#----------------------------------------------------------#

include $(COMMON)/startup/makefile
include $(COMMON)/api/makefile
include $(COMMON)/device/makefile
include $(COMMON)/stateos/makefile

#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
